=== noolex/sonic-mgmt-framework/CLI/clitree/scripts/sonic-clish.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2019 Dell, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<xs:schema xmlns="http://www.dellemc.com/sonic/XMLSchema"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xi="http://www.w3.org/2001/XInclude"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           targetNamespace="http://www.dellemc.com/sonic/XMLSchema">

<xs:import namespace="http://www.w3.org/2001/XInclude"/>

<xs:simpleType name="parammodeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="common"/>
    <xs:enumeration value="switch"/>
    <xs:enumeration value="subcommand"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="booleanType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="true"/>
    <xs:enumeration value="false"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="stringType">
<xs:restriction base="xs:string">
<xs:minLength value="0"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="hook_list_e">
<xs:restriction base="xs:string">
<xs:enumeration value="init"/>
<xs:enumeration value="fini"/>
<xs:enumeration value="access"/>
<xs:enumeration value="config"/>
<xs:enumeration value="log"/>
</xs:restriction>
</xs:simpleType>

<xs:attributeGroup name="commandAttr">
  <xs:attribute name="name" type="stringType" use="required"/>
  <xs:attribute name="help" type="xs:string" use="required"/>
  <xs:attribute name="ptype" type="stringType" use="optional"/>
  <xs:attribute name="view" type="stringType" use="optional"/>
  <xs:attribute name="viewid" type="stringType" use="optional"/>
  <xs:attribute name="view_names" type="stringType" use="optional"/>
  <xs:attribute name="namespace" type="stringType" use="optional"/>
  <xs:attribute name="access" type="stringType" use="optional"/>
  <xs:attribute name="mode" type="stringType" use="optional"/>
  <xs:attribute name="test" type="stringType" use="optional"/>
  <xs:attribute name="optional" type="booleanType" use="optional"/>
  <xs:attribute name="template" type="stringType" use="optional"/>
  <xs:attribute name="preprocess_xml" type="stringType" use="optional"/>
  <xs:attribute name="pfeature" type="stringType" use="optional"/>
  <xs:attribute name="args" type="stringType" use="optional"/>
  <xs:attribute name="args_help" type="xs:string" use="optional"/>
  <xs:attribute name="lock" type="stringType" use="optional"/>
  <xs:attribute name="template_param" type="stringType" use="optional"/>
  <xs:attribute name="default" type="stringType" use="optional"/>
  <xs:attribute name="escape_chars" type="stringType" use="optional"/>
  <xs:attribute name="interrupt" type="stringType" use="optional"/>
  <xs:attribute name="ref" type="stringType" use="optional"/>
  <xs:attribute name="error_option" type="stringType" use="optional"/>
  <xs:attribute name="test_option" type="stringType" use="optional"/>
  <xs:attribute name="skip_preprocess" type="booleanType" use="optional"/>
  <xs:attribute name="hidden" type="stringType" use="optional"/>
  <xs:attribute name="usageInfo" type="stringType" use="optional"/>
  <xs:attribute name="release" type="stringType" use="optional"/>
  <xs:attribute name="example" type="stringType" use="optional"/>
  <xs:attribute name="render_view" type="stringType" use="optional"/>
  <xs:attribute name="view_keys" type="stringType" use="optional"/>
  <xs:attribute name="view_tables" type="stringType" use="optional"/>
  <xs:attribute name="dbpath" type="stringType" use="optional"/>
  <xs:attribute name="render_command_cb" type="stringType" use="optional"/>
  <xs:attribute name="render_view_cb" type="stringType" use="optional"/>
  <xs:attribute name="data_and_render_cb" type="stringType" use="optional"/>
  <xs:attribute name="command_tables" type="stringType" use="optional"/>
  <xs:attribute name="db_flag" type="stringType" use="optional"/>
  <xs:attribute name="command_keys" type="stringType" use="optional"/>
  <xs:attribute name="render_command_viewid" type="stringType" use="optional"/>
</xs:attributeGroup>

<xs:attributeGroup name="paramAttr">
  <xs:attribute name="name" type="stringType" use="required"/>
  <xs:attribute name="help" type="xs:string" use="required"/>
  <xs:attribute name="ptype" type="stringType" use="required"/>
  <xs:attribute name="template" type="stringType" use="optional"/>
  <xs:attribute name="template_param" type="stringType" use="optional"/>
  <xs:attribute name="must" type="stringType" use="optional"/>
  <xs:attribute name="default" type="stringType" use="optional"/>
  <xs:attribute name="mode" type="parammodeType" use="optional"/>
  <xs:attribute name="pfeature" type="stringType" use="optional"/>
  <xs:attribute name="namespace" type="stringType" use="optional"/>
  <xs:attribute name="test" type="stringType" use="optional"/>
  <xs:attribute name="order" type="stringType" use="optional"/>
  <xs:attribute name="optional" type="booleanType" use="optional"/>
  <xs:attribute name="viewid" type="stringType" use="optional"/>
  <xs:attribute name="view" type="stringType" use="optional"/>
  <xs:attribute name="recursive" type="stringType" use="optional"/>
  <xs:attribute name="value" type="stringType" use="optional"/>
  <xs:attribute name="prefix" type="stringType" use="optional"/>
  <xs:attribute name="hidden" type="stringType" use="optional"/>
  <xs:attribute name="completion" type="stringType" use="optional"/>
  <xs:attribute name="access" type="stringType" use="optional"/>
  <xs:attribute name="dbpath" type="stringType" use="optional"/>
  <xs:attribute name="db_flag" type="stringType" use="optional"/>    
</xs:attributeGroup>

<xs:attributeGroup name="exampleAttr">
  <xs:attribute name="summary" type="stringType" use="optional"/>
</xs:attributeGroup>

<xs:attributeGroup name="altAttr">
  <xs:attribute name="type" type="stringType" use="required"/>
</xs:attributeGroup>

<xs:attributeGroup name="viewAttr">
  <xs:attribute name="name" type="stringType" use="required"/>
  <xs:attribute name="prompt" type="stringType" use="optional"/>
  <xs:attribute name="depth" type="stringType" use="optional"/>
  <xs:attribute name="access" type="stringType" use="optional"/>
  <xs:attribute name="restore" type="stringType" use="optional"/>

</xs:attributeGroup>

<xs:attributeGroup name="startupAttr">
  <xs:attribute name="view" type="stringType" use="required"/>
  <xs:attribute name="viewid" type="stringType" use="optional"/>
  <xs:attribute name="default_shebang" type="stringType" use="optional"/>
  <xs:attribute name="timeout" type="stringType" use="optional"/>
  <xs:attribute name="lock" type="stringType" use="optional"/>
  <xs:attribute name="interrupt" type="stringType" use="optional"/> 
  <xs:attribute name="default_plugin" type="stringType" use="optional"/>
</xs:attributeGroup>

<xs:attributeGroup name="actionAttr">
  <xs:attribute name="builtin" type="stringType" use="optional"/>
  <xs:attribute name="shebang" type="stringType" use="optional"/>
</xs:attributeGroup>

<xs:attributeGroup name="ptypeAttr">
  <xs:attribute name="name" type="stringType" use="required"/>
  <xs:attribute name="pattern" type="stringType" use="required"/>
  <xs:attribute name="help" type="xs:string" use="optional"/>
  <xs:attribute name="method" type="stringType" use="optional"/>
  <xs:attribute name="ext_pattern" type="stringType" use="optional"/>
  <xs:attribute name="preprocess" type="stringType" use="optional"/>
  <xs:attribute name="ext_help" type="xs:string" use="optional"/>
  <xs:attribute name="alt_pattern" type="stringType" use="optional"/>
  <xs:attribute name="alt_ext_pattern" type="stringType" use="optional"/>
</xs:attributeGroup>


<xs:attributeGroup name="namespaceAttr">
  <xs:attribute name="ref" type="stringType" use="required"/>
  <xs:attribute name="help" type="xs:string" use="optional"/>
  <xs:attribute name="prefix" type="stringType" use="optional"/>
  <xs:attribute name="completion" type="stringType" use="optional"/>
  <xs:attribute name="prefix_help" type="stringType" use="optional"/>
  <xs:attribute name="context_help" type="stringType" use="optional"/>
  <xs:attribute name="inherit" type="stringType" use="optional"/>
  <xs:attribute name="access" type="stringType" use="optional"/>
</xs:attributeGroup>


<xs:attributeGroup name="varAttr">
  <xs:attribute name="dynamic" type="stringType" use="required"/>
  <xs:attribute name="name" type="stringType" use="required"/>
  <xs:attribute name="value" type="stringType" use="optional"/>
</xs:attributeGroup>

<xs:element name="CLISH_MODULE" type="clishmoduleType"/>
<xs:element name="VIEW" type="viewType"/>
<xs:element name="COMMAND" type="commandType"/>
<xs:element name="STARTUP" type="startupType"/>
<xs:element name="ACTION" type="actionType"/>
<xs:element name="PTYPE" type="ptypeType"/>
<xs:element name="PARAM" type="paramType"/>
<xs:element name="DOCGEN" type="docgenType"/>
<xs:element name="DESCRIPTION" type="docgenStringType"/>
<xs:element name="FEATURE" type="docgenStringType"/>
<xs:element name="PLATFORM" type="docgenStringType"/>
<xs:element name="ALTCMD" type="altType"/>
<xs:element name="USAGE" type="usageType"/>
<xs:element name="EXAMPLE" type="exampleType"/>
<xs:element name="NAMESPACE" type="namespaceType"/>
<xs:element name="VAR" type="varType"/>
<xs:element name="HOOK" type="hookType"/>

<xs:complexType name="clishmoduleType">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="STARTUP" minOccurs="0"/>
    <xs:element ref="HOOK" minOccurs="0"/>
    <xs:element ref="PTYPE" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="COMMAND" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="VIEW" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="NAMESPACE" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="VAR" minOccurs="0" maxOccurs="unbounded"/>
  </xs:choice>
</xs:complexType>

<xs:complexType name="ptypeType">
  <xs:attributeGroup ref="ptypeAttr"/>
</xs:complexType>

<xs:complexType name="viewType">
  <xs:choice minOccurs="1" maxOccurs="unbounded">
    <xs:element ref="VAR" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="NAMESPACE" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="COMMAND" minOccurs="0" maxOccurs="unbounded"/>
  </xs:choice>
  <xs:attributeGroup ref="viewAttr"/>
</xs:complexType>

<xs:complexType name="startupType">
  <xs:sequence>
    <xs:element ref="ACTION" minOccurs="0"/>
  </xs:sequence>
  <xs:attributeGroup ref="startupAttr"/>
</xs:complexType>

<xs:complexType name="commandType">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="PARAM" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="ACTION" minOccurs="0" maxOccurs="1"/>
    <xs:element ref="DOCGEN" minOccurs="0" maxOccurs="1"/>
    <xs:any namespace="http://www.w3.org/2001/XInclude"
            processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
  </xs:choice>
  <xs:attributeGroup ref="commandAttr"/>
</xs:complexType>

<xs:complexType name="paramType">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="PARAM" minOccurs="0" maxOccurs="unbounded"/>
  </xs:choice>
  <xs:attributeGroup ref="paramAttr"/>
</xs:complexType>

<xs:complexType name="actionType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attributeGroup ref="actionAttr"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="docgenType">
  <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="DESCRIPTION" minOccurs="0" maxOccurs="1"/>
    <xs:element ref="FEATURE" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="PLATFORM" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="USAGE" minOccurs="0" maxOccurs="1"/>
    <xs:element ref="EXAMPLE" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="ALTCMD" minOccurs="0" maxOccurs="unbounded"/>    
  </xs:choice>
</xs:complexType>

<xs:complexType name="docgenStringType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="usageType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="exampleType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attributeGroup ref="exampleAttr"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="altType">
  <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attributeGroup ref="altAttr"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

<xs:complexType name="namespaceType">
  <xs:attributeGroup ref="namespaceAttr"/>
</xs:complexType>

<xs:complexType name="varType">
  <xs:sequence>
    <xs:element ref="ACTION" minOccurs="0"/>
  </xs:sequence>
  <xs:attributeGroup ref="varAttr"/>
</xs:complexType>

<xs:complexType name="hookType">
  <xs:attribute name="name" type="hook_list_e"/>
  <xs:attribute name="builtin" type="xs:string" use="optional"/>
</xs:complexType>
</xs:schema>

=== noolex/sonic-mgmt-framework/CLI/clitree/cli-xml/hardware_acl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2019 Broadcom. The term Broadcom refers to Broadcom Inc. and/or
its subsidiaries.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<CLISH_MODULE
    xmlns="http://www.dellemc.com/sonic/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xsi:schemaLocation="https://raw.githubusercontent.com/project-arlo/sonic-mgmt-framework/master/src/CLI/clitree/scripts/sonic-clish.xsd">

    <!--============================== CONFIG MODE COMMANDS ======================-->
    <VIEW name="configure-view">
        <!-- Global binding options -->
        <COMMAND name="hardware" help="Configure ASIC parameters" view="configure-hardware-view" data_and_render_cb="show_runn_hardware_cb"/>
    </VIEW>

    <VIEW name="configure-hardware-view" prompt="${SYSTEM_NAME}(config-hardware)# " depth="2">
        <COMMAND name="access-list" help="Configure ACL parameters" view="configure-hardware-acl-view" data_and_render_cb="show_runn_hardware_acl_cb"/>
    </VIEW>

    <VIEW name="configure-hardware-acl-view" prompt="${SYSTEM_NAME}(config-hardware-acl)# " depth="3">
        <COMMAND name="counters" help="Set ACL counters mode" data_and_render_cb="show_runn_hardware_acl_counter_cb">
            <PARAM name="counter-modes" help="" ptype="SUBCOMMAND" mode="switch">
                <PARAM name="per-entry" help="ACL counters are reported per ACL entry, aggregated across all interfaces" ptype="SUBCOMMAND" mode="subcommand" />
                <PARAM name="per-interface-entry" help="ACL counters are reported per interface and ACL entry" ptype="SUBCOMMAND" mode="subcommand" />
            </PARAM>
            <ACTION builtin="clish_pyobj">sonic_cli_acl set_counter_mode ${counter-modes}</ACTION>
        </COMMAND>
    </VIEW>

    <!--============================== EXEC MODE COMMANDS =======================-->
    <VIEW name="enable-view">
        <COMMAND name="show running-configuration hardware" help="Display current hardware configuration">
            <ACTION builtin="clish_pyobj">sonic_cli_show_config show_view views=configure-hardware</ACTION>
        </COMMAND>
        <COMMAND name="show running-configuration hardware access-list" help="Display current hardware ACL configuration">
            <ACTION builtin="clish_pyobj">sonic_cli_show_config show_view views=configure-hardware-acl</ACTION>
        </COMMAND>
    </VIEW>
</CLISH_MODULE>

=== noolex/sonic-mgmt-framework/CLI/clitree/cli-xml/vty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2019 Broadcom. The term Broadcom refers to Broadcom Inc. and/or
its subsidiaries.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<CLISH_MODULE
    xmlns="http://www.dellemc.com/sonic/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xsi:schemaLocation="https://raw.githubusercontent.com/project-arlo/sonic-mgmt-framework/master/src/CLI/clitree/scripts/sonic-clish.xsd">

    <!--============================== CONFIG MODE COMMANDS ======================-->
    <VIEW name="configure-view">
        <!-- Global binding options -->
        <COMMAND name="line" help="Session configuration" />
        <COMMAND name="line vty" help="Terminal type" view="configure-line-vty-view" />
    </VIEW>

    <VIEW name="configure-line-vty-view" prompt="${SYSTEM_NAME}(config-line-vty)# " depth="2">
        <COMMAND name="ip" help="Configure Internet Protocol (IP)"/>
        <COMMAND name="ipv6" help="Configure Internet Protocol v6 (IPv6)"/>

        <COMMAND name="ip access-group" help="Configure IPv4 ACL">
            <MACRO name="ACL-BINDING-OPTIONS-INGRESS" />
            <ACTION builtin="clish_pyobj">sonic_cli_acl bind_acl ${access-list-name} ACL_IPV4 ControlPlane ${direction-switch}</ACTION>
        </COMMAND>

        <COMMAND name="ipv6 access-group" help="Configure Internet Protocol v6 (IPv6)">
            <MACRO name="ACL-BINDING-OPTIONS-INGRESS" />
            <ACTION builtin="clish_pyobj">sonic_cli_acl bind_acl ${access-list-name} ACL_IPV6 ControlPlane ${direction-switch}</ACTION>
        </COMMAND>

        <COMMAND name="no" help="Negate a command or set its defaults"/>
        <COMMAND name="no ip" help="Configure Internet Protocol (IP)"/>
        <COMMAND name="no ipv6" help="Configure Internet Protocol v6 (IPv6)"/>

        <COMMAND name="no ip access-group" help="Configure IPv4 ACL">
            <MACRO name="ACL-BINDING-OPTIONS-INGRESS" />
            <ACTION builtin="clish_pyobj">sonic_cli_acl unbind_acl ${access-list-name} ACL_IPV4 ControlPlane ${direction-switch}</ACTION>
        </COMMAND>

        <COMMAND name="no ipv6 access-group" help="Configure Internet Protocol v6 (IPv6)">
            <MACRO name="ACL-BINDING-OPTIONS-INGRESS" />
            <ACTION builtin="clish_pyobj">sonic_cli_acl unbind_acl ${access-list-name} ACL_IPV6 ControlPlane ${direction-switch}</ACTION>
        </COMMAND>
    </VIEW>

    <!--============================== EXEC MODE COMMANDS =======================-->
    <!--<VIEW name="enable-view">
    </VIEW>-->
</CLISH_MODULE>
